name: chat

on:
  push:
    branch: [irc-chat]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        shell: bash 
        run: |
            docker buildx create --use
            docker buildx build --platform=linux/amd64 .  -t ghcr.io/mxlimbo/irc:chat --push
